<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppModelUserHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="custom_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['login'])) {
            $value = $data['login'];
            $return = (string) $value;
            $this->class->reflFields['login']->setValue($document, $return);
            $hydratedData['login'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['site_admin'])) {
            $value = $data['site_admin'];
            $return = (bool) $value;
            $this->class->reflFields['site_admin']->setValue($document, $return);
            $hydratedData['site_admin'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['company'])) {
            $value = $data['company'];
            $return = (string) $value;
            $this->class->reflFields['company']->setValue($document, $return);
            $hydratedData['company'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['blog'])) {
            $value = $data['blog'];
            $return = (string) $value;
            $this->class->reflFields['blog']->setValue($document, $return);
            $hydratedData['blog'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['location'])) {
            $value = $data['location'];
            $return = (string) $value;
            $this->class->reflFields['location']->setValue($document, $return);
            $hydratedData['location'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['email'])) {
            $value = $data['email'];
            $return = (string) $value;
            $this->class->reflFields['email']->setValue($document, $return);
            $hydratedData['email'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['bio'])) {
            $value = $data['bio'];
            $return = (string) $value;
            $this->class->reflFields['bio']->setValue($document, $return);
            $hydratedData['bio'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['hireable'])) {
            $value = $data['hireable'];
            $return = (bool) $value;
            $this->class->reflFields['hireable']->setValue($document, $return);
            $hydratedData['hireable'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['public_repos'])) {
            $value = $data['public_repos'];
            $return = (int) $value;
            $this->class->reflFields['public_repos']->setValue($document, $return);
            $hydratedData['public_repos'] = $return;
        }
        return $hydratedData;
    }
}